### ISSUE TITLE
Better way to fix cheating

### ISSUE THREAD

**Issue by Mooisthebest** [ThoreBor/Anki_Leaderboard#100]
Hi, A way to fix cheating would be to add a "Hide" function. This allows the user to determine themselves if they are cheating or not. The fix to sort by time spent did not account for users that have sketchy retention times nor does it account for removing their rank so everyone else can be adjusted for 1st-3rd placements. This can also remove abusive/offensive usernames so it's a double+ whammy. 

--add a "hide user" function, that adjusts rank afterwords. i.e #1 hidden, leaderboards now show everyone below moved up 1 rank. 
--add a "show all hidden" function so they can undo their hides if they wanted to (accidental, things changed, etc)

Some other things that would be ideal but after the above is done first:
--add a "request a group" option, to add groups that you approve. i.e Pre-USMLE STEP 1 & Post USMLE STEP 1
--Add a note section (i.e Character limit 140) next to user name as last column. In note, people can put their groupme/IG/social media/Medical School (similar to clan in gaming lol) to add one another to message on there. This avoids needing servers/etc to hold conversations within anki. 
--When I open the leaderboard, retention is the last column and I have to readjust every time I open to include it in the window. Please increase window size to include retention time as well. 
--Add Weekly reviews done
--Add number of 1, 2, 3 places in the past 31 days
--Add a calendar function. Button->Selection date (Default today), allowing to see the next day who really got 1,2,3 place in case you were unable to check later that night. 
--Default everyone world wide to PST or EST somewhere between 12AM-3AM to add consistency. Yes some people's cards will be moved to the next day instead of the day of but if they anki consistently this shouldn't matter. 
--Enlarge 1, 2, 3 places. I. e double row width

Lastly I wanted to say thank you A LOT for this add-on. I've been wanting this for ever and it is definitely pushing me to anki more so thank you!

**Comment by ThoreBor** [comment]
Thanks for your suggestions, great 100th issue!

- Hide function: Great idea, I'll definitely implement that. 
- "Note section" is also a nice addition, but I'm not going to show it on the leaderboard in an extra column. My idea is that you'll be able to click on a user and a new window opens with the "note section", a "hide user" option, and maybe some other stuff.
- "request a group" is basically already done (#95) I coded everything and it's also already here on GitHub, but I'll update it so that I have to "confirm" the new group to avoid spam.
- Window size: Could you send me a screenshot? The table/window size should normally be adjusted automatically
- Weekly reviews: In the next update I'll add leagues (see #93). A season would last two weeks at the moment. So on the league leaderboard, you would see more long term stats. I don't think I'll add weekly reviews to the leaderboards. For most people, weekly reviews is probably roughly reviews past 31 days / 4, so I think it would be kinda redundant.
- Because I only save the latest data from every user I currently can't tell who got 1st, 2nd, 3rd, etc. place "yesterday". Yesterday is pretty relative with all the timezones. The first place "yesterday" could've synced after "yesterday" again and would no longer be first place. I can't keep track of that at the moment. And I don't understand what you mean by:
> Default everyone worldwide to PST or EST
- I'll try to double the row width, but I'm not sure if I can do it

I'm glad to hear that. Thanks for all your input!
