### ISSUE TITLE
Sync between different Anki profiles ?

### ISSUE THREAD

**Issue by shaggy-debug** [ThoreBor/Anki_Leaderboard#109]
If we can do reviews in two profiles, can the code be changed so that leaderboard takes stats from both the profiles ?

I have two separate profiles due to card types error.

I complete 500 reviews in one and close to 1000 in another, but the leaderboard just shows only stats from one profile !!

**Comment by ThoreBor** [comment]
The add-on can only access the database of the profile that is currently active, so keeping track of the stats between multiple profiles is difficult. I'll keep it in mind, but it's a low priority since most users probably won't benefit from this.

**Comment by shaggy-debug** [comment]
Yes, please try to change it whenever you can. 

Maybe I can run different Leaderboard profiles for different Anki profiles. It will be easy if you can just add a logout feature just below the login.

If I don't logout from one Leaderboard profile and just switch to different ANKI profile, and then log in into different LEADERBOARD profile both the leaderboard profiles seem to be using the same stats. 

![image](https://user-images.githubusercontent.com/55146601/96328999-7de80b80-1066-11eb-834e-7a46f9ba51cb.png)

**Comment by TeacherBrian** [comment]
Having this functionality would be very helpful.  

I am a teacher who is using Anki with a group of students.  Since Anki has a bit of a steep learning curve, I manage their Anki accounts.  Leaderboard was a gamechanger for me because it allows for healthy competition between students.  The current problem that I face is that I need to switch profiles and then log in to each student's account on leaderboard for their stats to be updated.  It would be great if there were somehow a more efficient way to do this.  

And thank you so much for this addon!

**Comment by ThoreBor** [comment]
I'm sorry, but I probably won't implement this anytime soon. The add-on files are shared between profiles, so I would have to keep track of different profiles and their respective configurations. I don't really know how I would go about adding this at the moment. And because most people only use one profile, I don't think it's worth the effort.
The best solution would probably be to eventually make your students manage their own accounts. 
Just a heads up, I didn't really test using the add-on with so many profiles. So there might occur some unexpected bugs, but it should probably work.

**Comment by TeacherBrian** [comment]
Thank you Thore for your response.  I appreciate it.

I understand your reasoning for not wanting to implement this anytime soon.

Thank you anyways.  Leaderboard is a great add-on.  It has been great for
my class and has added an element of competition that the students like.
