### ISSUE TITLE
Leaderboard league didn't get updated properly for me

### ISSUE THREAD

**Issue by aah-yeets** [ThoreBor/Anki_Leaderboard#112]
**Describe the bug**
The league got updated today but I am still in the Delta league after getting consistent 40s rank daily

**Screenshots**
![Screenshot 2020-10-16 at 9 03 24 PM](https://user-images.githubusercontent.com/72987754/96279069-da5e1300-0ff3-11eb-9f71-3e5e2e3ac0d6.png)
![Screenshot 2020-10-16 at 9 02 39 PM](https://user-images.githubusercontent.com/72987754/96279087-de8a3080-0ff3-11eb-828a-9c71b25b2ecf.png)

**Steps to reproduce bug**
Not sure. Tried to reset the app many times.

**Info**
- Anki version 2.1.28
- Leaderboard version 1.6.0
-
- OS: Using Anki on the Linux (Beta) of a Chromebook

**Additional context**
Friends with similar and lower ranks have passed onto the Next league.
Could you please take a look at this?
Thank you so much for this amazing add-on btw

**Comment by ThoreBor** [comment]
Thanks for letting me know. There seems to be bug, but I'm not sure what the issue is. In the backup right before I updated the leagues you (I'm assuming it's IMS YEET) have 0 xp. But I checked another backup from today at 7:46 am UTC you had 3003521 xp (50th). So I'll put you into the Gamma league in a moment.
I'll look into the issue. It would be great if you could provide some more context on how this problem occurred. When do you do your reviews, when do you sync etc.

**Comment by aah-yeets** [comment]
Thanks for the prompt response.
I usually do my reviews starting at 9 pm (GMT+5:30) and sync 3-4 times in between (to check my rank and get some motivation).
On the day of the league change I probably checked it 5-7 times, but it showed the season is going to end soon at all times.
Please let me know if you want to know anything further.

**Comment by ThoreBor** [comment]
Alright, thanks. It's probably not something you did. I'll do some tests and see if I can find the issue.

**Comment by ThoreBor** [comment]
If you're using v1.6.1 or v1.6.2 there shouldn't be a problem this season. Please let me know if something still went wrong.

**Comment by aah-yeets** [comment]
I'm using v1.6.2 and did not face any problems.
Thank you for the great and quick fix.
