### ISSUE TITLE
Post installation pop-up error!

### ISSUE THREAD

**Issue by WoodsMacdonalds** [ThoreBor/Anki_Leaderboard#116]
I downloaded the add-on via code and re-opened anki and this message poped up! Currently using Anki version 2.1.15 (Can't update it because I'm using windows 7), Please help me! I wasted the whole day trying to fix it! Tried turning off the add-ons but won't work!
**Screenshots**
Error message:
![image](https://user-images.githubusercontent.com/73300226/96891073-f7ca2b80-1490-11eb-844b-0a9184e892e4.png

Thank you so much!

**Comment by ThoreBor** [comment]
Yes, someone else already reported this to me. It will be fixed in the next update (probably in the next few days). Until then you unfortunately can't use the add-on with Anki 2.1.15. If you want to you can download v1.5.3 [here](https://github.com/ThoreBor/Anki_Leaderboard/releases/tag/v1.5.3) (open the .ankiaddon file). Since it's an older version some newer features are missing, though.

**Comment by WoodsMacdonalds** [comment]
I would rather wait for the new fix! I'm really excited to use it! 
Thank you so much!

**Comment by WoodsMacdonalds** [comment]
I did try using the .ankiaddon file for the mean time tho, and this poped up!
![image](https://user-images.githubusercontent.com/73300226/97019917-928e3d00-1559-11eb-9774-b4299ecca5f5.png)

**Comment by ThoreBor** [comment]
I'm pretty sure that this has nothing to do with the add-on. Looks like you tried to import cards from a txt file that wasn't formatted properly.

**Comment by WoodsMacdonalds** [comment]
Thanks ThoreBor!
Just a note for those using windows 7/Older versions of anki, either update anki or use v1.5.3 .ankiaddon file. 
If the leaderboard is installed but doesn't work (Connection timeout), consider downloading a VPN and try agin.
