### ISSUE TITLE
Anki becames very slow when using LeaderBoard as a main screen table

### ISSUE THREAD

**Issue by abedahmeduhp** [ThoreBor/Anki_Leaderboard#118]
**Describe the bug**

**Screenshots**

**Steps to reproduce bug**
LeaderBoard > Config > Show LeaderBoard on the main Screen
So Anki became very very slow 
**Info**
- Anki version (Help>About; e.g. 2.1.26)
- Leaderboard version (Leaderboard>Config>About tab; e.g. v.1.4.4)
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: (e.g. Linux Mint)

**Additional context**
I

**Comment by ThoreBor** [comment]
I'm assuming it's slow when you return to the home screen? That's probably because the leaderboard is reloading and requests data from the server. This shouldn't take a long time, but might be noticeable. Thanks for letting me know. I might try to reduce the number of server requests in the future. That could improve the performance, but occasionally the add-on has to send and receive data. If it's bothering you, disable the home screen leaderboard (and also auto sync). That way Ankis performance won't be affected.

**Comment by MaximeLeFloch** [comment]
Ha damn, I just posted the same issue again, sorry didn't see that one.
I have the same issue on ubuntu.
