### ISSUE TITLE
Medals next to Usernames and league management

### ISSUE THREAD

**Issue by Bob132639** [ThoreBor/Anki_Leaderboard#122]
It would be great if the people who end up in the Gold, Silver, Bronze positions get a permanent medal(s) of some kind that people can see next to their username. (Maybe just limit this to the top league, though). 

I have more suggestions, but I'll wait until people get distributed into the 4 leagues to see how it all works out first.

Sidenote, this is one of my favorite add-ons 🥇

**Comment by ThoreBor** [comment]
That's an interesting idea. The easiest way to do this would probably be to just add emojis to their names (🥇,🥈and🥉). Or what did you have in mind? If those medals would be permanent and not just from the previous season it would probably make sense to also add the season to the medal. Something like `username | 🥇 Season 2`. And if it's not just from the top league some indication from which league the medal is would seem necessary. But I feel like displaying all this next to the username could clutter up the leaderboard. Adding it to the user info window wouldn't be a problem. What do you think?

I'm happy to hear that. Looking forward to the suggestions, it's going to take a few more seasons to distribute all the users more or less evenly.

**Comment by Bob132639** [comment]
I think putting it in their profile seems to be an easy solution where you can add the more specific information like season number and the division medals. 

But I was initially thinking more along the lines of a dedicated column for medals that only tally a total of the golds, silvers, and bronzes, like an "at a glance major achievements" outside of just making it to the division. Say "3🥇, 2🥈" or "1🥇, 3🥉". That could be just limited to the top division for exclusivity.

Yeah, I think the main future suggestion is a revamp of the XP equation so it encourages better and more precise use of ANKI (I looked up the exact equation and i've already changed my EaseFactor add-on to get more bang for my buck just for the League XP, haha), but that's all stuff to think about once the distribution of people if better between divisions and we see how it pans out.

**Comment by Bob132639** [comment]
I thought I might as put down my thoughts on the XP equation even if there's no rush to change it until the divisions distribute a little. 

So the equation now is XP = (400 x Time x Retention) + (200 x Reviews x Retention) 

1) I think you should openly post the equation somewhere so everyone is on the same page. I calculated it because it's relatively simple right now, but I feel being open about it as it gets more complicated is the best practice going forward. The equation is a huge impact on incentives going forward for anyone taking the league seriously. That means it's paramount that it encourages good Anki practices. 

2) I think the time multiplier is still not high enough because I doubt anyone takes 30 seconds on average per card. I am usually between 8-12 seconds per card. That means if my retention is 100%, I get about 400 x 100 x 1 = 40,000 per minute but 200 x 100 x 5 = 100,000 per minute (low end) from reviews. There's no problem with incentivizing easier cards (that aligns perfectly with good Anki practice), but some people will simply be using Anki in a way that they will have to spend more time: Ie. Any subject will have more complicated cards than say language learning where you can rattle off 20 cards per minute on average. So my suggestion here is to have it 3x instead of 2x, so 

XP = (600 x Time x Retention) + (200 x Reviews x Retention). 

3) Right now there is HUGE incentive to having higher retention. The higher you have, the better your score. Anki isn't about having perfect retention, though. In fact, I'd argue 85%-90% is actually ideal for card spacing and adding new content. So my suggestion is to simply have ranges: 

If it's between 80-100%, you get the full 100% multiplier. 
If it's between 60-80%, you get a 75% multiplier. 
If it's between 40-60%, you get a 50% multiplier. 
If it's between 20%-40%, you get a 25% multiplier. 
If it's between 0%-20%, you get a 0% multiplier. 

I would also just set it as 100% for time because retention is only really about reviews. So:

XP = (600 x Time) + (200 x Reviews x Retention Bracket)

4) Lastly, I'm thinking we should add streaks as an important component because Anki is all about consistency, daily reviews, and keeping up with your reviews when it's their ideal time to be reviews. My suggestion is that we just add a multiplier on the entire score based on your highest steak of that 2-week period. You'd have to add a new column for the top streak for the season so far for each person (not sure if that's doable because I vaguely remember the add-on not remembering anything itself). Could lower the influence and make it their entire streak instead of the 2-week streak if that's not doable. Or maybe base it on the percentage of days studied in the last 2 weeks or year or something (I have no idea what info you have access to, but I know there are other add-ons that track this) 🤔😂

XP = Streak x ((600 x Time) + (200 x Reviews x Retention Bracket)) 

I feel like these changes are a really good step in the right direction. Eventually the equation would fully reflect the 20 rules of Anki or some other "perfect Anki practice" set of rules (as best as possible) to align incentives with best Anki practice as closely as possible. 

Also I'm not sure why the XP numbers have to be so high, haha. Might have to bring the 600 and 200 down to 300-100 or even an even lower multiple just so the scores don't get ridiculously high now with the Streak multiplier.

**Comment by ThoreBor** [comment]
Thanks for all your suggestions! In my opinion, adding a whole column for medals would be overkill, because only a small percentage of users is going to have medals, especially if you only could get medals if you're in the top league. So for most users, this column would be empty and be "wasted" space. What I think could work is adding e.g. 3🥇, 2🥈 next to the username and then put additional info (season, maybe league) in the user info window. Now that I'm thinking about it, adding the place (and maybe xp) from the previous season(s) for every user might also be interesting. What do you think?

Regarding the calculation of xp:
You put way much thought into this than I did! The only thing I tried to keep in mind was that time spend reviewing should be more important than the number of reviews done because some users suggested it. I first wanted to see how it goes and then adjust it in the future. So far nobody complained though and I didn't have a better idea yet.

The equation you calculated isn't correct actually. You can find the correct one [in the api.py file](https://github.com/ThoreBor/Anki_Leaderboard/blob/e91561fd9f09c0521398018eb85544005472c992/server/api.py#L82). `(4 x time + 2 x reviews) x retention`. So it's not a secret, but you're right I should probably include it in the about tab for example.

I agree with your second point and that's pretty much in line with what other users suggested. But I now realize that with the current equation, even though time is twice as "important", most users probably get more XP for reviews than time spend studying. This is definitely something that should be fixed. 

I also like your retention approach. This makes more sense. Maybe I would change the steps from 20% to 15% but I'm not sure. Although Anki isn't about having perfect retention and for a lot of users it might not be close to that, especially when they're doing a lot of new cards, but I do think that someone with a retention rate in the upper nineties should have a slight advantage to someone with a retention rate in the lower eighties.  With the current equation, everyone with 0 retention doesn't get any xp, which I think isn't right, but so far it doesn't seem to be a problem.

Including streaks wouldn't be a problem. I didn't include them because I thought using the current streak would give new Anki users a big disadvantage. But using the longest streak within the current season would be great and I just didn't think of that.

Just a side note: XP are being calculated on the server. That way I can update the equation without having everyone download a new version of the add-on. However, adding streaks would require a new update unless it's an all or nothing situation, where you would get "bonus points" for studying all 14 days and no bonus points if you missed a day (because the current streak gets synced, so if it's >=days-since-the-season-started you get the points). But I think an update would be necessary, even if just for adding the column. There might be some issues because not everyone regularly updates the add-on but it should probably work out. 

Thanks again for your suggestions and let me know what you think, or if you have any other ideas.

**Comment by Bob132639** [comment]
That works as well, but you'll have to ban the use of emojis in usernames because some people are already using medals in there 👍 

Oh, the equation is the same, just put in a different form: 
(400 x Time x Retention) + (200 x Reviews x Retention) = (4 x Time + 2 x Reviews) x Retention (I had it as the decimal equivalent for the percentage and you have it as whole numbers for the percentage. That's why its 2 and 4 for you and 200 and 400 for me) 

I generally disagree that higher retention is better because it's very much a user preference and dependent on the content you are studying and outcome you want and also some add-ons like "Auto-Ease Factor" means you can change it any time you want to any percentage without even noticing. But y could make the retention brackets smaller, though, say 10%, and then there is the difference between having 98% and 82% that you want. I wouldn't worry too much about retentions lowers than 50% tbh because it's almost impossible to have it that low after 30 minutes of study (and if it is that low, you aren't using the software properly for sure because the cards must be waaaay too complicated).

The more I think of it, the more I think a percentage of days you did in the 14-day season is a better multiplier than streaks (if it's still easy to implement). Kinda like a retention percentage multiplier but in terms of numbers of days worked in the season. Otherwise, the 2-week streak is still a good option. I guess the bonus system could work as well, but it doesn't sound as precise and would have to be changed every time the equation is updated to be the right numbers.

Updates should be fine 🤷‍♂️ as long as there's an announcement? Probably just coincide it with a new season starting.

**Comment by ThoreBor** [comment]
> That works as well, but you'll have to ban the use of emojis in usernames because some people are already using medals in there 👍

Yeah, I also noticed that. No problem.

> Oh, the equation is the same, just put in a different form

Ah, I see. Sorry. 

You got a point. I think I'll go with the smaller brackets.

> The more I think of it, the more I think a percentage of days you did in the 14-day season is a better multiplier than streaks

I like it. I'll do it like that. I'm not exactly sure how yet, but it's definitely possible.

I'm going to use `XP = Streak percentage x ((600 x Time) + (200 x Reviews x Retention Bracket))` then.

Implementing all of this shouldn't take too long, but I'm not sure how much time I'll have next week. I'll try to get it done before the next season starts. Maybe I'm going to delay the start of the next season for a day or two and make an announcement so everyone or at least most people update. Otherwise, some users will have 0 xp because the streak percentage would be 0.

**Comment by Bob132639** [comment]
👌

No rush, though 🙂 I haven't gotten my butt to do much work on Anki for at least a week now, so it's not like it'll impact me much down in Delta 😂

Wouldn't it be 1/1 before their name is included for the current season? I always see the divisions get more and more populated as the season goes one and people do work (or sync?)

Again, thanks for all this. I think your work is going to have a big impact on the number of people who use Anki and stick with it in the future.

**Comment by ThoreBor** [comment]
> Wouldn't it be 1/1 before their name is included for the current season?

Sorry, I don't really understand what you mean.

Yes, a lot of users don't sync daily (and there are of course also new users), so the longer the season goes on the more users there are normally. 

Thanks for the kind words and thanks for your input :)

**Comment by Bob132639** [comment]
You said their streak percentage would be 0. I thought people weren't included until they sync and that coincides with doing some Anki so they'll have at least a 1 streak from the get-go. I'm probably misunderstanding.

**Comment by Bob132639** [comment]
Ohhhh, I get it. That makes sense. That's why the pause between seasons so most people read the announcement and do a proper update without being in an instant disadvantage.

**Comment by ThoreBor** [comment]
Right, although updating later is not a disadvantage. The stats for the entire season get synced no matter when you sync. But I think it would be better to make the announcement and wait until most people are using the newest version to avoid confusion.

**Comment by Bob132639** [comment]
I agree.

First, I was thinking about the streak percentage and was thinking there should be a lower time/card limit to include a day in the streak percentage (if that's possible) seeing as leagues are competitive and having people log 5 cards just to keep the streak percentage up is a bit silly. I'm thinking something along the lines of 10 minutes / 50 cards. It's low enough to be easily done even if you are busy that day but high enough that it's not the case of basically just logging in and pretending you did something, haha. 


Second, I've been playing with the numbers of people in each division just to see how quickly the numbers distribute using the 20% promotion 20% relegation rule.

So there are around 900 people participating right now. That means it's going to slowly approach 225 people/division if we exclude new participants. My guess is that every season will add between 15-30 new participants but that really is a guess cus I have no data. I projected the distributions going forward with a +20 new participants each season and it'll take about 7 seasons to have a distribution like this:

Alpha: 107 
Beta: 180 
Gamma: 303
Delta: 433
Total: 1023

It looks pretty good. I guess the two choices at this point is just to let those 4 divisions increase participants and slowly become equal OR you could try to keep the exclusivity of the top division and start adding more divisions every time the top division hits a certain number of people, say 100 or 200. So in the 100-limit top division case Season 8 would be:

Epsilon: 21 (yeah, the names don't work as well now, haha)
Alpha: 100 
Beta: 190
Gamma: 304
Delta: 427
Total: 1043

Then Season 9:

Epsilon: 37
Alpha: 103
Beta: 195
Gamma: 306
Delta: 422
Total: 1063

Project this forward to Season 16 and you have:

Using the current system:

Alpha: 226
Beta: 264
Gamma: 332
Delta: 421
Total: 1243

Using a 100-person limit where it splits in the top division:

Zeta: 44
Epsilon: 89
Alpha: 153
Beta: 228
Gamma: 316
Delta: 412
Total: 1243

Just big picture things to consider regarding the shape of the divisions going forward and your preference 💁‍♂️

**Comment by ThoreBor** [comment]
I think doing at least 10 minutes of Anki for it to be counted as a "day learned" is a good idea. I'll do it like this.

Thanks for your ideas. I thought about this as well. Adding more divisions wouldn't be a problem. But I think this is not super urgent so I'll wait a couple more seasons until I decide what to do. 
There are significantly more new participants per season. I just checked some logs and since November 9th 373 new accounts were created (58 deleted). I don't know how many of those are active though. 

Just a little update: I'm basically done with implementing the medals, but I haven't started with the new xp etc. Here some screenshots. Let me know what you think.

![image](https://user-images.githubusercontent.com/40232329/99883144-bced1c00-2c25-11eb-841c-31de89263885.png)

![image](https://user-images.githubusercontent.com/40232329/99883151-d2fadc80-2c25-11eb-92e7-19886a57f1ce.png)

![image](https://user-images.githubusercontent.com/40232329/99883161-e3ab5280-2c25-11eb-9b66-d876032b3213.png)

![image](https://user-images.githubusercontent.com/40232329/99883272-af846180-2c26-11eb-81e7-d13adfd560f8.png)

**Comment by Bob132639** [comment]
"this is not super urgent so I'll wait a couple more seasons until I decide what to do." - Very true. 

"I just checked some logs and since November 9th 373 new..." Wow, I didn't realize it was this much, but I fully understand why the add-on is so popular, and it'll only gain more traction the more positive reviews it gets in the add-on page.

I was curious about the way the usernames don't show up until it syncs. Is there a way to show the usernames using the prior season info and place them under the active participants until they sync for the new season? Then everyone can see how big the division actually is without waiting until the end of the season when most people are actively seen participating (admittedly it's not all that important). Also, I'm presuming the relegation includes usernames that haven't shown up that season because their score is technically 0?

Looks reaaaallly good, though👌 Great work!

**Comment by ThoreBor** [comment]
I guess I could just put everyone with 0 xp at the bottom in a "grey area" or something like that. But using data from the previous season might be confusing. 
> Also, I'm presuming the relegation includes usernames that haven't shown up that season because their score is technically 0?
No, if you don't sync in a season you just don't participate. Your league doesn't change after the reset.

Just so you know, I won't be able to release the update before the start of the next season. I just don't have enough time. But I'm sure I'll get it done in the next two weeks.

**Comment by Bob132639** [comment]
All good 👍

I thought of something else. 

I'm not sure if this is intentional or not but in all the the other tabs (Global, Friends, Country, Custom) you can rank people according to any of the title columns (username, reviews, time, streak, retention), but in the League tab it is frozen to the ranking (clicking the column titles causes it to be selected for a second but doesn't change anything).

**Comment by ThoreBor** [comment]
Yes, this is intentional. The idea is that you can sort Global, Friends, Country, and Groups in whatever order you want/you're most interested in, but in leagues there really only is one "correct" way to rank users - xp.

And I think that showing users with 0 xp at the bottom is not such a good idea after all. I just checked, and technically there are over 3000 people in Delta. I think less than a third participated in the last season, so it's probably not very helpful to show them all. It might be worth it in Gamma, Beta, and Alpha because the all users to active users ratio is much better.

Btw. it looks like awarding medals and saving the results for every user after the end of the season worked. And I also just committed the code for adding "days learned" to the league tab, home screen etc. Seems to work fine. Like you suggested you have to study for at least 10 minutes per day.

**Comment by Bob132639** [comment]
Okay, cool, just checking.

Wow. That's a lot of people.

From what I can tell, the 20% promotion/relegation rule applies only to participants in that particular season, not everyone in the division. I think that's a little off. It makes sense for Delta league where you only want 20% of participants to promote and not 20% of the whole 3000 (which would be basically anyone who participated), but in Gamma, Beta, Alpha divisions, it's kind of like punishing someone who did a little (or even quite a lot in higher divisions) and letting someone who did nothing keep his/her place. You get what I mean? And then, in conjunction, it makes sense to have the 0 XP people included from the get-go in the upper divisions because they will be participating in the the relegation. 

Great! Looking forward to next season. Hopefully I can get out of Delta division for the change :)

**Comment by ThoreBor** [comment]
So I just checked a backup to find out the exact numbers for last season:

Delta total: 3488
Delta active: 956

Gamma total: 435
Gamma active: 264

Beta total: 66
Beta active: 51

Alpha total: 7
Alpha active: 6

I get what you mean. I think the best approach is probably to include users with 0xp in Gamma, Beta, and Alpha but not Delta. So that way inactive users will eventually end up in delta and won't bother anyone.

**Comment by Bob132639** [comment]
Maybe set it as anyone who gets 0 XP is relegated:

The two main options I see after that are between applying the 20% rule to the rest (non-0 XP people) or applying it to the total people (as long as it's higher than total number of 0 XP people because they will be relegated anyway).

If we use an example of 200 people and 150 participants:

In scenario 1 it would be 80 relegations (50 non-participants + 30 participants) and 30 promoted 
In scenario 2 it would be 50 relegations (just the 0 XP people because 50 > 40) and 40 promotions

**Comment by ThoreBor** [comment]
I'll try scenario one for now and see how it goes. Thanks again for your help.

The question is now when would be the best time to release this update? I'd say the update is basically ready (unless you have something else). I could release it during this season and apply the changes above at the end of the season. 
"Days studied" would be included in the league tab but wouldn't affect XP yet. I could then change the XP equation on the server after the season is over and the next one could start on time. Or should I wait until the season's over?

**Comment by Bob132639** [comment]
I initially wrote to wait for mechanical changes and only do cosmetic changes to give people time, but I don't think the leagues are that serious yet that it's even worth waiting. From what I can tell, all the divisions (even the higher 2) only have about 50% participation rate so far this season. So, yeah, just implement everything you can straight away. People will get used to it when it's already in practice and it's early enough in the league development in general that there shouldn't be much fuss. I would say the way you announce changes does matter quite a bit, though.

Is there a way to set up an announcement page when you click the leaderboard tab before it shows the leaderboard? That would be a much more concise and wide-reaching way of telling people the changes than them having to go to addons -> info.

**Comment by ThoreBor** [comment]
Right, I also think the sooner the better. I'll get ready to release it then. Probably over the weekend.

Yes, I actually thought ahead and implemented a notification function back in v1.4.5. So I'll use this to announce the update and the changes.

**Comment by Bob132639** [comment]
Looks like it's gone really well 👌

Unfortunately there's no way to look at the divisions outside of your own so I can't look and see how it looks outside of lowly Delta, haha. (Although I'm not sure if that's even visible different until season 6 starts when the relegation group is bigger)

The only thing I can think of is that the initial column width for "Days Studied %" is too narrow when it first loads up. Is there a way to have it automatically open up in a bigger window because the small window is causing that? Could be on my side, though.

**Comment by ThoreBor** [comment]
> Unfortunately there's no way to look at the divisions outside of your own

Yes, I might change that in the future. For now, you can only check it on the website.

Do you have a screenshot of that? Looks fine on my end and it should automatically adjust.

Everyone who has, or tries to have "🥇", "🥈", "🥉" and "|" in their usernames got/will get a message that that's not allowed anymore and that they should contact me if they want me to change their username, or make a new one if they don't care. 

Unfortunately, it looks like there's a bug in the streak calculation for some users. I think I found the problem, just waiting for confirmation. So there's probably/hopefully going to be another update later today.

**Comment by Bob132639** [comment]
![image](https://user-images.githubusercontent.com/74370950/101470031-c4126a80-3945-11eb-8260-11184f35e1b5.png)

This is window when I open it up (I use a Mac). It's obviously not a big deal but figured it would be an easy fix.

**Comment by ThoreBor** [comment]
Okay, thanks. I'll make the window a bit wider then while I'm at it.

**Comment by robinlucidarme1234** [comment]
Hi, is there a manual how to configure the different accounts and users? If not, can someone sent a couple of screenshots and I can make a user manual and upload here.
