### ISSUE TITLE
Days Studied not correct 

### ISSUE THREAD

**Issue by Lenticulostriate** [ThoreBor/Anki_Leaderboard#139]
**Describe the bug**
It says that my days studied is <100% when my streak has been 100%.

**Screenshots**

![image](https://user-images.githubusercontent.com/66183413/112791015-38246b80-9026-11eb-995c-bee7b4fc5171.png)

![image](https://user-images.githubusercontent.com/66183413/112791059-512d1c80-9026-11eb-87ef-390dc5664526.png)
(darker blue squares have less reviews but there are still 300+ reviews). 

**Info**
- Anki version: v2.1.22
- Leaderboard version: v1.6.3.1
- If relevant Add-on config info: 7 hrs after mid-night
- OS: Windows 10

**Additional context**
Destroys league points bc days studied is in calculation.

**Comment by ThoreBor** [comment]
A day only counts as "studied" in leagues when you studied for at leat 10 minutes. Could this be the issue?

**Comment by Lenticulostriate** [comment]
IDK because it went from 100 to 90% yesterday, and I had 400+ minutes yesterday.

**Comment by Lenticulostriate** [comment]
So its back at 100% now but around 8:00PM CST it drops back down to 90%.

**Comment by ThoreBor** [comment]
Okay, thanks. I'll look into it

**Comment by buster-blue** [comment]
> A day only counts as "studied" in leagues when you studied for at leat 10 minutes. Could this be the issue?

I was about to make a new issue myself about days learned not being counted on the leaderboard, but I think this is the problem. I keep a small number of cards that I have to review each day because I'm often busy, but I wanna make sure that I'm able to do my cards every day. Because of this, the time studied each day is usually around 7 minutes, and that's probably why my days studied ratio is only 25% even though I study every day.

Could this restriction be relaxed to 5 minutes counting as a day studied? Or maybe have it so that if all review cards are finished, it counts the day as studied, even if it hasn't been 10 minutes yet? Otherwise, my ratio will probably never get to a decent number with how small I like to keep the number of cards I do.

**Comment by Oafish1** [comment]
I'm having a similar issue.  I've studied under 10 minutes a maximum of 3 times in the past 80 days and not at all in the past month.  I do a ton of reviews late (in the AM) at night.  I'm in CST.  My days learned is reported as 85% for the season.  Does the 10 minutes not count learning/new cards maybe?

**Comment by ThoreBor** [comment]
The bug should be fixed in the next update (it'll hopefully be released in the next few days). I also reduced the minimum study time to 5 minutes. 
Please let me know if you still have the problem after the update.
