### ISSUE TITLE
Viewing previous days and a monthly leaderboard

### ISSUE THREAD

**Issue by Charlotte-R-01134** [ThoreBor/Anki_Leaderboard#146]
Being able to go back and see the previous days leaderboard would be really cool. My friends and I do them at different times so we don't always get to check the leaderboard.

Also, being able to view a monthly leaderboard would be a cool feature to have. Seeing an average etc

**Comment by ThoreBor** [comment]
Hi, it looks like you're not the only one that would find this useful (see #144, #82, #75). I think I'll try to implement an option to check yesterday's results, but it's gonna take a while because I have to change a lot for it. I assume you'd be interested in all the stats, right? Or just something specific?
I'm not sure about the monthly leaderboard though. There already are leagues for long-term-ish competition and the reviews past 31 days column.

I'll close this issue because it's a duplicate. If you could comment in #144 that'd be great.
