### ISSUE TITLE
Unable to open leaderboard add-on after installing latest update

### ISSUE THREAD

**Issue by wangsusa** [ThoreBor/Anki_Leaderboard#190]
**Describe the bug**
After installing the latest leaderboard add-on update, I restarted Anki and received the attached error message. Now I cannot open the leaderboard add-on at all. I used to be able to click on "Leaderboard" at the top of my screen, but now I can't even access it through Tools -> Add-ons. I already tried deleting the add-on and reinstalling it and I still have the same error message and the same issue of not being able to open the leaderboard at all. 

**Screenshots**
See screenshot attached.
<img width="418" alt="PNG image" src="https://user-images.githubusercontent.com/121773252/210186641-bd19496a-5a5b-48ab-8c7a-24efe9d8dc3a.png">

**Steps to reproduce bug**
Happens every time I tried to start Anki.

**Info**
- Anki version: 2.1.44
- Leaderboard version (Leaderboard>Config>About tab; e.g. v.1.4.4)

<img width="651" alt="Screen Shot 2023-01-01 at 5 48 41 PM" src="https://user-images.githubusercontent.com/121773252/210186726-402a708c-4fed-41ee-a46b-e821c52d267e.png">

- OS: Mac OS Monterey 12.6

**Additional context**
n/a

**Comment by ThoreBor** [comment]
Thanks for reporting this! Looks like it only works on Anki 2.1.50 and higher. I'll make sure to only roll out updates for those versions in the future and keep lower versions on Leaderboard v2.1.0.  I recommend updating Anki, because I'm not planning to support Leaderboard v2.x for much longer.
In the meantime you can download Leaderboard v2.1 from [here](https://github.com/ThoreBor/Anki_Leaderboard/releases). Download the .ankiaddon file from the assets and open it to downgrade to that version.
