### ISSUE TITLE
cannot reset my password

### ISSUE THREAD

**Issue by azxcqer** [ThoreBor/Anki_Leaderboard#204]
**Describe the bug**
I've used this extensions a few while back. I can't remember my password and I can't reset it at all. similar to issue #200 I've tried every e-mail I have to no avail. I also do not remember adding an e-mail to the account at all. Was there a time where it was optional? could it be that my account has no e-mail associated to it at all?

**Screenshots**
![image](https://user-images.githubusercontent.com/14042262/220918774-74e913be-5b39-45c0-89c4-663ec820db00.png) here is an screenshot showing that I'm actually logged in but it asks for me to re-login to authenticate and I'm unable to.
![image](https://user-images.githubusercontent.com/14042262/220919649-1ae65a16-34f4-4846-bf8d-556013519a57.png) the error it gives when trying to set the bio asking for authentication

**Steps to reproduce bug**
If possible, step by step instructions for how to reproduce the bug

**Info**
- Anki version Version ⁨2.1.58 (ab8b1465)
- Leaderboard version 3.0.2
- OS: linux

**Additional context**
I do like the user name but if nothing can be done about it it is fine too. I can always just start a new account but more people could have some similar issues so I'm opening an issue about it.

**Comment by ThoreBor** [comment]
Yes, this is probably an issue because you updated from an old account. Up until v3.0 you could migrate old accounts, but in the newer versions it is not supported anymore. 
If you're still logged in (it looks like you might be), you could try to download [v2.1.0](https://github.com/ThoreBor/Anki_Leaderboard/releases/tag/v2.1.0) and go to Leaderboard>Config>Account>Update old account. You could also send me an email ([leaderboard_support@protonmail.com](mailto:leaderboard_support@protonmail.com)) with your `meta.json` file and I'll try to fix it for you. You can find the file by going to Tools>Add-ons>Leaderboard>View Files
