### ISSUE TITLE
ankidroid sync

### ISSUE THREAD

**Issue by philomorphism** [ThoreBor/Anki_Leaderboard#222]
**Describe the bug**
the leaderboard doesn't sync from the annkidroid

**Steps to reproduce bug**
- study few cards on ankidroid
- sync to cloud
- open anki on pc, sync from cloud
- check the leaderboad, it's not showing what you studied
- study few cards on pc anki
- check the leaderboard and it's all fine now

**Info**
- Anki version: 2.1.66
- Leaderboard version: 3.0.2
- OS: Ubuntu

**Additional context**
I checked other issues, though there were some ankidroid sync issues, I couldn't find the exact issue i have, I apologize if it turns out to be a duplicate.

**Comment by XinYaanZyoy** [comment]
so, I figured, the leaderboard does sync from the Android. but we have to manually sync the leaderboard once we're on the PC.

I expected behavior:
settings for when to sync the leaderboard with the following possible options:

1. sync the leaderboard whenever the ankidroid/pc is synced to Ankiweb
2. sync the leaderboard every time an anki client (mobile/pc, even web?) is either opened or closed.

**Comment by Antside** [comment]
Sorry but how exactly do you do this? I hit the sync button and yet my streak still appears as 0
