### ISSUE TITLE
pressing enter to add friend: successfully created account

### ISSUE THREAD

**Issue by khonkhortisan** [ThoreBor/Anki_Leaderboard#23]
Leaderboard→Config→Friends→Add Friend: typing their name and clicking Add Friend would add them as a friend, but typing their name and pressing enter says Successfully created account. This sets Tools→Addons→Leaderboard→config→username to "" and removes the green highlight on the global tab. Since the blue highlight update, instead of removing the green highlight entirely, it turns it blue. Putting the username back in Tools→Addons→Leaderboard→config→username doesn't immediately restore the green highlight, but Leaderboard→Config→Login does.

**Comment by ThoreBor** [comment]
Thanks for letting me know. The create button is selected by default, so you created an "empty" account, which deleted your username in the config. You're also by default your own friend, so since you didn't have a username after creating this account you only showed up as a friend on the leaderboard. I'll try to fix it.

**Comment by zjosua** [comment]
I suggest using a QTabWidget in the config dialog. You could also add an about tab, instead of making "About" a separate dialog.
@ThoreBor, do you create the forms with QT Designer? If yes, could you add the .ui files to the repo and if not, would you accept a PR to include .ui files and build the python code for the forms with pyuic (or even [aab](https://github.com/glutanimate/anki-addon-builder))?

**Comment by ThoreBor** [comment]
Yes, I could do that. And yes I'm using Qt Designer. I'll upload the ui. files right away.
