### ISSUE TITLE
Anki 2.1.23 compatibility

### ISSUE THREAD

**Issue by p4nix** [ThoreBor/Anki_Leaderboard#38]
**Describe the bug**
Compatibility has been set to Anki 2.1.22 with the new update. As far as I can tell, Anki 2.1.23 is only a bugfix for Mac OS users concerning non-latin alphabet usage in file names and shouldn't affect add-on coding. As I'm not familiar with the Anki source code, I can't verify that, but if that's true it would be cool if compatibility would be set to Anki 2.1.23 again - so that mac users can benefit from your add-on as well :)

Thanks for making it. Although I am definitely not on the competitive side, it's interesting to see how other people are doing.

**Comment by ThoreBor** [comment]
In #33 somebody had a fatal error using the add-on with anki 2.1.24, so I set the compatibility to 2.1.22, because that's the version I'm using. I can't guarantee that it'll work on later versions. You can now download the add-on, even if you're using >2.1.22, but I can not officially support the newer mac versions at the moment.

**Comment by ThoreBor** [comment]
zjosua fixed this with #39

**Comment by p4nix** [comment]
As it is fixed now anyway, I guess it's not a matter anymore. But otherwise, Anki 2.1.23 is essentially Anki 2.1.22 for Mac OS X with a minor bugfix and shouldn't affect add-on compatibility between Anki 2.1.22 <=> Anki 2.1.23.

https://github.com/ankitects/anki/compare/2.1.22...2.1.23

Thanks again for your work and for re-adding Mac OS support 👍
