### ISSUE TITLE
Sorting error

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#66]
Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-29 13:49:37

Exception in thread Thread-78:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 1254, in run
  File "D:\Anki\Anki.2.1.data\addons21\41708974\Leaderboard.py", line 249, in load_leaderboard
    self.dialog.Global_Leaderboard.item(0, j).setBackground(QtGui.QColor("#ffd700"))
AttributeError: 'NoneType' object has no attribute 'setBackground'
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Timer(Thread-78, started 7188)>>
Traceback (most recent call last):
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 934, in _bootstrap_inner
  File "threading.py", line 1212, in invoke_excepthook
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by ThoreBor** [comment]
Without any context it's difficult to say what went wrong. It looks like there was an error while highlighting the first three places. What did you do when this error occurred?

**Comment by cjdduarte** [comment]
When I open the addon window and leave the ranking open for a few minutes.

**Comment by cjdduarte** [comment]
I got it (steps):
1. Select the friends tab;
2. I ordered by the "Review today" column (2 clicks)
3. I waited for the addon to update (2 minutes);
4. When sorting by names, the error occurs.

**Comment by ThoreBor** [comment]
Okay, I suspected something like this. I'll fix it.

**Comment by ThoreBor** [comment]
You now have to opt-in to refresh the leaderboard. This also disables sorting. I think sorting by anything other than reviews while studying isn't that interesting. This fixes the issue temporarily. I keep this issue open though. Maybe somebody else has a better idea how to solve this, or I can come up with a better solution.
The issue is, that sorting messes with the leaderboard when it tries to repopulate the table. More info [here](https://stackoverflow.com/questions/7960505/strange-qtablewidget-behavior-not-all-cells-populated-after-sorting-followed-b/31444019). Some columns are empty which throws an error in the highlight functions.
