### ISSUE TITLE
Head to Head with friends

### ISSUE THREAD

**Issue by hamnad2** [ThoreBor/Anki_Leaderboard#82]
Would be nice to add head to head leader board especially with friends, let's say for last week. or month. 

Like you won in total cards 3 times and he won 4 times. and so on. 

would that be possible?

**Comment by ThoreBor** [comment]
That's a good idea but it isn't possible with the current database, because it only saves the latest sync (similar to #75 ). I'll try to implement it in the future, but it'll probably take a while.
To decrease the amount of data I would have to store on the server, I might start saving some data locally instead.

**Comment by ThoreBor** [comment]
I'll close this and use #144 to address this.
