### ISSUE TITLE
I can't open Leaderboard to even create an account

### ISSUE THREAD

**Issue by djsmitty** [ThoreBor/Anki_Leaderboard#91]
I just added leaderboard to my anki and every time I try to open it it comes up with an error message.
<img width="424" alt="Screen Shot 2020-07-07 at 12 22 52 PM" src="https://user-images.githubusercontent.com/67977694/86832370-f2b1af80-c04c-11ea-8a09-7e1bd887c005.png">

**Comment by ThoreBor** [comment]
Yes, I'm aware of the problem, but there's nothing I can do about it. Pythonanywhere's servers are currently down, that's why the add-on can't access the database. Hopefully, they'll resolve the problem soon. They are rebooting everything at the moment. You can check the newest updates on their twitter: https://twitter.com/pythonanywhere
