### ISSUE TITLE
Fix cheating please

### ISSUE THREAD

**Issue by adaptivejohnny** [ThoreBor/Anki_Leaderboard#93]
Hello,

Firstly thank you for this add on, it really motivates me. But it has come to my attention people are just abusing the leaderboard add on. For instance today there was a guy at the number 1 spot globally with 2876 reviews but only 28.2 minutes spent? thats not fair or right.

I think what could be done is to have the leaderboard be sorted by time spent instead of reviews, to stop people who would click just to be on top of leaderboards. This wont solve all of the cheating but i think it could stop a lot. This would also make things fairer to everyone as time does not discriminate against types of cards, it just takes into account the amount of time you actually spent studying. For instance one individual could be doing very simple cards while others could be doing more challenging cards, of course the guy with simpler cards would do more reviews meanwhile the guy with the harder cards is going slower but probably is spending way more time actually studying.

Now people could still cheat this way but i think it would be substantially harder just because you have to spend way more time trying to achieve a bigger time rather than doing nearly 3k reviews in less than 30 mins.

Thank you for your time and i hope this makes some sense. I pasted an image of the leaderboard with the cheaters.

![image](https://user-images.githubusercontent.com/40969951/87253055-0f335a80-c446-11ea-8aaf-d7c0789d9043.png)

**Comment by ThoreBor** [comment]
Hi,
yes, I also noticed that. I think sorting by time is a good idea. I'll probably change it in the next update. 
I'm not accusing him/her of cheating, but I'd say that this many cards in such a short amount of time is quite unrealistic. I mean it's over 100 cards per minute. Unfortunately, it's not that difficult to sync fake data to the server as discussed in issue #26 and there's not much I can to about it (at least not that I can think of).

**Comment by ThoreBor** [comment]
I just released a new update. For now, you can choose in the config what the leaderboard should be sorted by.

**Comment by bluescarf** [comment]
Auto-sorting by time is a great idea. Thanks for the update! 

On a related note, we have columns for "reviews today" and "reviews for past 31 days". Are there any plans for making a comparable longer-term column for time studied; something like "hours studied over the past 31 days"? I feel like that would be incredibly useful, given that review time is a less biased indicator of long-term Anki usage compared to review counts.

**Comment by adaptivejohnny** [comment]
Thank you ThoreBor for updating that. Also i think another useful feature could be having something analogous to an "Employee of the Month" where the individual with the most time spent per day/week/month would have their name on the leaderboard homepage. Call it "Champion of the Day" or week or month. You will give the award to person who has spent the most time. By doing this, you will legitimize that sorting by time method is the default method.

What do you think? just an idea. I also like bluescarfs idea as well.

**Comment by ThoreBor** [comment]
Thanks for your suggestions! 

My plan at the moment is to implement some sort of "league system". 
I'm haven't decided on the details yet, but I think that this would solve some of the problems. Right now I'm thinking of something like this:
- there are several leagues, everyone starts in the lowest one and tries to get into the next one
- you can get into the next league by finishing the "season" (two weeks, a month, idk) in the top 10% of the league leaderboard (last 10% could drop a league)
- the league leaderboard is sorted by XP
- XP are going to be calculated based on time spent, reviews and average retention
- the stats would be the total number of cards, total amount of time etc. since the start of the season
- at the end of the season, I could announce the best users in each league + some stats

What do you think? I'm open for ideas. 

![image](https://user-images.githubusercontent.com/40232329/87456558-67658a80-c607-11ea-9984-84a5ab12775c.png)
